### ISSUE TITLE
请问Bangumin.tv的统计功能还在正常获取数据吗？

### ISSUE THREAD

**Issue by Adiwon** [edwardez/BangumiN#20]
我在今年9月、10月都有活动，但bangumin.tv的统计页面一直显示上次数据更新在2018年9月5日。统计数据中“总计”一项的数据好像更新过，看着是最新的，但其它数据都停留在上述日期。

**Comment by edwardez** [comment]
数据更新过了，再试试看？

这个数据现在只能同步全部，同步一遍要好几天所以是每隔一段时间手动跑的，有想法让用户可以手动请求更新某个人的数据改成但目前暂时没时间做。
