### ISSUE TITLE
可以手动更改域名吗？

### ISSUE THREAD

**Issue by asnml** [edwardez/BangumiN#38]
&emsp;&emsp;使用应用时访问速度很慢，然后想到 Bangumi 是有三个域名的，如果应用是使用网页的 API 的话，那么是否可以手动更改访问的域名来达到最佳访问速度？

**Comment by edwardez** [comment]
感谢建议:)
结论上来说，目前没有想到很好的办法。
bangumi有三个域名，`bangumi.tv`,`chii.in`和`bgm.tv`，三个都在境外，访问速度都不是很快，bangumi.tv`和`chii.in`是一个服务器，所以我们只用讨论`bangumi.tv`和`bgm.tv`。

目前app采取的是从`bangumi.tv`抓取网页和通过`api.bgm.tv`访问api相结合的方法

通过`api.bgm.tv`访问api，主要影响收视管理，用户个人主页和搜索条目: 没有很好的方法改善，官方只提供了这个地址（有一些不稳定的方法，比如向bangumi.tv发送假header从而使用bangumi.tv的api -- 我觉得这已经有点算欺诈了，或者自己开反向代理 - bangumi有请求限制，反向代理会被限制）

从`bangumi.tv`抓取网页，主要影响讨论页，帖子，时间线: 理论上可以提供通过`bgm.tv`的访问，但出于某些原因`bgm.tv`[禁止](https://github.com/edwardez/BangumiN/commit/f901f1cde4b9a80f04b6195a1502f07f0c059e9a)从bangumin里抓取网页，这个问题很严重，但我没法稳定复现，所以目前没办法提供通过`bgm.tv`的访问

作为参考，“使用应用时访问速度很慢”是访问哪些页面时很慢，不使用代理访问`bangumi.tv`或`bgm.tv`是类似的速度吗，还是会变快？

**Comment by asnml** [comment]
感谢回答，原来已经考虑到了吗，是我太想当然了_(:з」∠)_
访问速度慢主要在于讨论页，较为常出现请求超时，使用代理时有较好改善，另进度页有时也会出现番剧头像无法加载的情况。
提出这个问题的原因在于，我的PC端访问 `bangumi.tv` 时速度极慢，而访问 `bgm.tv` 时却十分流畅。APP的动态页以及主页虽然能保证稳定访问，但访问速度却不及 PC 端访问 `bgm.tv` 时的速度，于是便有了以上的提问。
